In [1]:
# The convention is to import pandas shortcut as pd
import pandas as pd
data = pd.read_csv('2018CrimeStatisticsByCategoryOfCrime.csv')

In [3]:
data.iloc[11:24]

,Unnamed: 0,Unnamed: 1,REPORTED CASES,Unnamed: 3,Unnamed: 4,Unnamed: 5,PERFOMANCE,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
11,NaN,ECONOMIC CRIMES,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,9,Embezzlement,199,172,19,8,48,3,-,-,...,-,-,-,"3,000,000",178,-,13,-,"54,403,285,118","602,281,000"
13,10,Causing Financial losss,58,49,6,3,18,-,-,-,...,-,-,-,-,56,-,2,-,"21,829,723,334","35,094,000"
14,11,Abuse of office,50,39,11,-,10,-,-,-,...,-,-,-,-,44,-,1,-,"5,589,167,545","487,000,000"
15,12,Counterfeiting,541,215,159,167,244,51,1,30,...,-,13,9,"700,000",416,3,164,-,"226,405,000","13,577,000"
16,13,Forgeries & Uttering of Documents,898,525,186,187,378,52,5,26,...,-,1,5,"19,490,000",713,3,125,-,"776,721,600","77,321,000"
17,14,Issuing False Cheques,344,221,80,43,142,9,-,4,...,-,6,-,"4,800,000",283,-,69,-,"46,659,863,708","1,369,076,200"
18,15,Bank and Other Corporate Frauds,17,15,1,1,6,-,-,-,...,-,-,-,-,15,-,2,-,"1,075,338,441","42,870,000"
19,16,Obtaining By False Pretences,"12,313","5,776","3,936","2,601","4,637",817,51,389,...,1,107,123,"72,330,000","9,525",9,"2,807",5,"121,253,215,820","18,452,845,505"
20,17,Cyber (Computer) crimes,198,142,40,16,40,6,-,2,...,-,2,3,"700,000",149,-,51,-,"610,335,098","23,317,000"
21,18,Land Frauds,345,171,124,50,173,9,4,7,...,-,-,2,"26,000,000",272,-,78,-,"735,920,000","8,250,000"
22,19,Other Economic crimes,136,86,13,37,50,5,-,9,...,-,-,-,"400,000",124,-,22,-,"3,769,213,107","125,626,500"
23,NaN,Sub Total(Economic crimes),"15,099","7,411","4,575","3,113","5,746",952,61,467,...,1,129,142,"127,420,000","11,775",15,"3,333",5,"256,929,188,771","21,237,258,205"