In [1]:
# The convention is to import pandas shortcut as pd
import pandas as pd
data = pd.read_csv('2018CrimeStatisticsByCategoryOfCrime.csv')

In [2]:
data.iloc[101:107]

,Unnamed: 0,Unnamed: 1,REPORTED CASES,Unnamed: 3,Unnamed: 4,Unnamed: 5,PERFOMANCE,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
101,NaN,POLITICAL/MEDIA OFFENCES,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,82,Incitement to Violence,181,81,66,34,67,4,1,7,...,-,-,18,-,171,-,11,-,-,-
103,83,Promoting Sectariasm,4,3,-,1,2,-,-,-,...,-,-,-,-,4,-,-,-,-,-
104,84,Election Offences,249,97,110,42,101,5,2,11,...,-,3,4,"1,200,000",215,1,25,-,-,-
105,85,Treason,8,5,-,3,4,-,-,-,...,-,-,-,-,6,-,-,-,-,-
106,NaN,Sub Total(Political/Media),442,186,176,80,174,9,3,18,...,-,3,22,"1,200,000",396,1,36,-,-,-